### ISSUE TITLE
Generate Content for Cat and SubCat

### ISSUE THREAD

**Issue by JoeWrightNC** [schmitty890/homestead#37]
Do what it says, that way we'll be ready to style the pages accordingly when we get to writing.

**Comment by schmitty890** [comment]
We will have to consider on how we want to add this content.

i just added https://github.com/schmitty890/homestead/issues/38

options are, we could make a handlebars template as stated in that story.
1. could hardcode the categories/subcats
2. could in our controller/api-routes/, read from the database, some category or items table, and pass those values to the handlebars template, populating the template with the most popular categories.

this could get tricky through, as we'd need to find a way to calculate up the most popular cats, and then the most popular subcats, to those cats.

**Comment by JoeWrightNC** [comment]
I think we hardcode for community, classified, and skill share since the user won't be able to add new categories for those, only declare which one their post goes into.  If we get to making a forum, we should try method 2 there. @schmitty890

**Comment by schmitty890** [comment]
@JoeWrightNC  agreed. we could take it one step further, and instead of hardcoding the cats and subcats directly into our handlebars template, and create a static json file with all of our cats and subcats. then pass that json object through the handlebars template to render that portion of the page.

this approach would allow us to update the top categories and subcats easier compared to updating them within the handlebars template itself.
